_defaults:
  default_scoring: &default_scoring
  - completed_before: 2700
    percent: 100
  50_percent_before_30: &50_percent_before_30
  - completed_before: 1800
    percent: 50
  - completed_before: 2700
    percent: 50
  50_percent_before_20: &50_percent_before_20
  - completed_before: 1200
    percent: 50
  - completed_before: 2700
    percent: 50
  50_percent_before_35: &50_percent_before_35
  - completed_before: 2100
    percent: 50
  - completed_before: 2700
    percent: 50
  50_percent_before_40: &50_percent_before_40
  - completed_before: 2400
    percent: 50
  - completed_before: 2700
    percent: 50
  34_percent_before_20_30: &34_percent_before_20_30
  - completed_before: 1200
    percent: 34
  - completed_before: 1800
    percent: 33
  - completed_before: 2700
    percent: 33
  34_percent_before_30: &34_percent_before_30
  - completed_before: 1800
    percent: 34
  - completed_before: 2700
    percent: 66
  75_percent_before_35: &75_percent_before_35
  - completed_before: 2100
    percent: 75
  - completed_before: 2700
    percent: 25

# replace with actual key
flask_secret_key: topsecret

quest:
  teams:
  - name: Команда 1
    id: team1
    password: team1p
  - name: Команда 2
    id: team2
    password: team2p
  - name: Команда 3
    id: team3
    password: team3p
  - name: Команда 4
    id: team4
    password: team4p
  - name: Команда 5
    id: team5
    password: team5p
  - name: Команда 6
    id: team6
    password: team6p

  admins:
  - name: Admin
    id: admin
    password: admin

  stages:
  - name: Етап 0
    duration: 600000

    tasks:
    - id: task_0_1
      name: Початок
      code: glhf
      max_points: 0
      scoring:
      - completed_before: 600000
        percent: 100
      counts_towards_total_time: False

  - name: Етап 1
    duration: 2700
    message: "<b>Інтерактивна частина квесту: <a href='https://vseosvita.ua/webquest/start/s/19358/3608570-657a816a'>vseosvita.ua</a></b>"

    tasks:
    - id: task_1_1
      name: №1
      code: "186624"
      max_points: 30
      scoring: *34_percent_before_20_30
    - id: task_1_2
      name: №2
      code: "14"
      max_points: 30
      scoring: *34_percent_before_30
    - id: task_1_3
      name: №3
      code: "2518114"
      max_points: 30
      scoring: *34_percent_before_30
    - id: task_1_4
      name: №4
      code: "47"
      max_points: 30
      scoring: *34_percent_before_20_30
    - id: task_1_5
      name: №5
      code: "Свята"
      max_points: 20
      scoring: *75_percent_before_35
    - id: task_1_6
      name: №6
      code: "Бог"
      max_points: 20
      scoring: *75_percent_before_35
    - id: task_1_7
      name: №7
      code: "Одяг"
      max_points: 20
      scoring: *75_percent_before_35
    - id: task_1_8
      name: №8
      code: "Ноги"
      max_points: 20
      scoring: *75_percent_before_35
    - id: task_1_9
      name: №9
      code: "трійка"
      max_points: 20
      scoring:
      - completed_before: 2100
        percent: 25
      - completed_before: 2400
        percent: 50
      - completed_before: 2700
        percent: 25
    - id: task_1_10
      name: №10
      code: "Штані"
      max_points: 20
      scoring:
      - completed_before: 2520
        percent: 75
      - completed_before: 2700
        percent: 25
    - id: task_1_11
      name: №11
      code: "Піфагор"
      max_points: 50
      scoring:
      - completed_before: 2580
        percent: 70
      - completed_before: 2700
        percent: 30
    - id: portal_1
      name: Портал
      code: "Гурман*д*"
      max_points: 10
      scoring: *default_scoring

    hints:
    - text: "Хмм, щось це схоже на золоту спіраль... Золото, переріз, трикутник..."
      timing: 1200
    - text: "Це ж золотий трикутник загаданий! А у нього цікаві кути є - вони підкорюються співвідношенню 2:2:1. І ще у нього є кут 36 градусів."
      timing: 1800
    - text: "Вкрали 14 колес."
      timing: 1800
    - text: "Тут є декілька рішень, але одне з найпростіших - це 4."
      timing: 1800
    - text: "Які круті трикутники: Вони ж прямокутні! А тут ще і піфогорові трійки є..."
      timing: 1200
    - text: "Там невідомі сторони 35 та 12."
      timing: 1800
    - text: "Свята"
      timing: 2100
    - text: "Бог"
      timing: 2100
    - text: "Одяг"
      timing: 2100
    - text: "Ноги"
      timing: 2100
    - text: "хмм, Бог з святим щось.... О, Піфагор згадав одну фразу що і бог і святий ... і хтось ще. Як їх гурт називається (але вже без слова свята)?"
      timing: 2100
    - text: "Це трійка"
      timing: 2400
    - text: "Це штані!"
      timing: 2520
    - text: "Це Піфагор, не впізнали?"
      timing: 2580

  - name: Етап 2
    duration: 2700

    tasks:
    - id: task_2_1
      name: №1
      code: "23"
      max_points: 20
      scoring:
      - completed_before: 1200
        percent: 75
      - completed_before: 2700
        percent: 25
    - id: task_2_2
      name: №2
      code: "210391,206"
      max_points: 25
      scoring:
      - completed_before: 1200
        percent: 60
      - completed_before: 2700
        percent: 40
    - id: task_2_3
      name: №3
      code: "Дзеркальце"
      max_points: 30
      scoring: *34_percent_before_20_30
    - id: task_2_4
      name: №4
      code: "The_Times"
      max_points: 20
      scoring: *50_percent_before_20
    - id: task_2_5
      name: №5
      code: "Пі"
      max_points: 10
      scoring: *50_percent_before_20
    - id: task_2_6
      name: №6
      code: "Каспій"
      max_points: 30
      scoring: *50_percent_before_35
    - id: task_2_7
      name: №7
      code: "напій"
      max_points: 30
      scoring: *50_percent_before_35
    - id: task_2_8
      name: №8
      code: "Паскаль"
      max_points: 30
      scoring: *50_percent_before_35
    - id: task_2_9
      name: №9
      code: "Пікассо"
      max_points: 30
      scoring: *50_percent_before_35
    - id: task_2_10
      name: №10
      code: "спосіб"
      max_points: 30
      scoring: *50_percent_before_35
    - id: task_2_11
      name: №11
      code: "піна"
      max_points: 30
      scoring: *50_percent_before_35
    - id: task_2_12
      name: Фінал
      code: 'Навіть-"Паскаліна"-нам-не-потрібна-коли-все-настільки-ізі-пізі'
      max_points: 5
      scoring: *default_scoring
    - id: portal_2
      name: Портал
      code: "The_true_crime"
      max_points: 10
      scoring: *default_scoring

    hints:
    - text: "Це дуже відомі вирази одного з філософів, але десь вони змінені. Хмм, а як бінарне обозначення правди та брехні можна перевести у число..."
      timing: 1200
    - text: "Відповідь: 210391,206"
      timing: 1200
    - text: "так, ні, так, ні, так, так, ні, так. Чи здогадаєтесь як це стосується до завдання?"
      timing: 1200
    - text: "20-19+35-145+39+90-21-1+13=11"
      timing: 1800
    - text: "У інженера ділове взуття, у коваля сандалі. Що залишається?"
      timing: 1200
    - text: "Хммм, а які цікаві константи знаєте ви? Такі, щоб вони записувались літерою..."
      timing: 1200
    - text: '"К" літері "А" приставили "спій"'
      timing: 2100
    - text: '"На" "пі" строїть "й". Цікаво, що це означає...'
      timing: 2100
    - text: 'Пі - і + Аска (героїня одного з найвідоміших мультфільмів) + нота "соль" - ль.'
      timing: 2100
    - text: "пі + касса, але остання літера стала о."
      timing: 2100
    - text: "с + пі - і + оса - а + пі - п + б."
      timing: 2100
    - text: '"Пі" стоїть "на" чомусь.'
      timing: 2100

  - name: Етап 3
    duration: 2700
    message: "<b>Друга частина Квесту: <a href='https://vseosvita.ua/webquest/start/s/19358/3608570-657a816a'>vseosvita.ua</a> <br> Етап 2: Портал на телевізорі, ключ: Ліна_Паскаліна</b>"

    tasks:
    - id: task_3_1
      name: Ключ+замок
      code: "Жовтий_Феррарі"
      max_points: 50
      scoring: *default_scoring
    - id: task_3_2
      name: Метр квадратний
      code: "фізика"
      max_points: 20
      scoring: *default_scoring
    - id: task_3_3
      name: Площа тризуба
      code: "247"
      max_points: 50
      scoring: *default_scoring
    - id: task_3_4
      name: Кількість коренів
      code: "нуль"
      max_points: 20
      scoring: *default_scoring
    - id: task_3_5
      name: Завдання з портретами
      code: "занадто_круті"
      max_points: 70
      scoring: *default_scoring
    - id: task_3_6
      name: Рівняння в координатах
      code: "теорема_Вієта"
      max_points: 70
      scoring: *default_scoring
    - id: task_3_7
      name: Шарада
      code: "карданний_вал"
      max_points: 20
      scoring: *default_scoring
    - id: portal_3
      name: Портал
      code: "Паскаліна_не_відьма"
      max_points: 0
      scoring: *default_scoring

  - name: Етап 4
    duration: 2700
    message: "<b>Етап 3: Портал у Рапунцель, ключ: Ньютон+Лейбніц=інтеграл</b>"

    tasks:
    - id: task_4_1
      name: №1
      code: "loooooooooool2023"
      max_points: 70
      scoring: *default_scoring
    - id: task_4_2
      name: №2
      code: "philox2015"
      max_points: 20
      scoring: *default_scoring
    - id: task_4_3
      name: №3
      code: "takeMeWithYouPlease"
      max_points: 40
      scoring: *default_scoring
    - id: task_4_4
      name: №4
      code: "gaussTop1ever"
      max_points: 40
      scoring: *default_scoring
    - id: task_4_5
      name: №5
      code: "sudoku228"
      max_points: 70
      scoring: *default_scoring
    - id: task_4_6
      name: №6
      code: "5bulls0cows"
      max_points: 60
      scoring: *default_scoring
    - id: portal_4
      name: Портал
      code: "klyatiPogramistu"
      max_points: 0
      scoring: *default_scoring

  - name: Етап 5
    duration: 2700
    message: "<b>Етап 4: Портал на лампі справа, ключ: dostatnioMatematuku</b>"

    tasks:
    - id: task_5_1
      name: Гільберт
      code: "ch23427"
      max_points: 25
      scoring: *50_percent_before_35
    - id: task_5_2
      name: Оппенгеймер
      code: "openheimer72634"
      max_points: 35
      scoring: *default_scoring
    - id: task_5_3
      name: Dota2
      code: "dots16749"
      max_points: 35
      scoring: *50_percent_before_40
    - id: task_5_4
      name: Мудрець
      code: "dots78972"
      max_points: 25
      scoring: *50_percent_before_40
    - id: task_5_5
      name: Ріман
      code: "everyone765234"
      max_points: 50
      scoring: *50_percent_before_30
    - id: task_5_6
      name: Шредінгер
      code: "qubit578204"
      max_points: 40
      scoring: *50_percent_before_35
    - id: task_5_7
      name: Вікторина
      code: "lang634094"
      max_points: 40
      scoring: *default_scoring
    - id: task_5_8
      name: Фібоначчі
      code: "bigo850433"
      max_points: 50
      scoring: *50_percent_before_35
    - id: portal_5
      name: Портал
      code: "portal106784"
      max_points: 0
      scoring: *default_scoring

    hints:
    - text: "Це набагато легше, ніж парабола - базова арифметика"
      timing: 2100
    - text: "-rw-r--r-- ▸ -(011)(010)(010) ▸ ???"
      timing: 2400
    - text: "How to exit vim?"
      timing: 2400
    - text: "Модульна арифметика"
      timing: 1800
    - text: "А яке значення має обертання навколо полюса, якщо нам туди і треба?"
      timing: 2100
    - text: "Матриця в степінь - логарифмічний час"
      timing: 2100

  - name: Етап 6
    duration: 2700
    message: "<b>Етап 5: Портал на рубіні зліва, ключ: wow640813</b>"

    tasks:
    - id: task_6_1
      name: №1
      code: "author"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_2
      name: №2
      code: "pink"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_3
      name: №3
      code: "troll"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_4
      name: №4
      code: "divide"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_5
      name: №5
      code: "math"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_6
      name: №6
      code: "never"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_7
      name: №7
      code: "bone"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_8
      name: №8
      code: "dog"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_9
      name: №9
      code: "equation"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_10
      name: №10
      code: "twelve"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_11
      name: №11
      code: "laugh"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_12
      name: №12
      code: "equals"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_13
      name: №13
      code: "twelve author troll dog bone laugh math equation equals divide pink never"
      max_points: 120
      scoring: *default_scoring
    - id: portal_6
      name: Портал
      code: "666"
      max_points: 0
      scoring: *default_scoring
