_defaults:
  default_scoring: &default_scoring
  - completed_before: 2700
    percent: 100

# replace with actual key
flask_secret_key: topsecret

quest:
  teams:
  - name: Команда 1
    id: team1
    password: team1p
  - name: Команда 2
    id: team2
    password: team2p
  - name: Команда 3
    id: team3
    password: team3p
  - name: Команда 4
    id: team4
    password: team4p
  - name: Команда 5
    id: team5
    password: team5p
  - name: Команда 6
    id: team6
    password: team6p

  admins:
  - name: Admin
    id: admin
    password: admin

  stages:
  - name: Етап 0
    duration: 600000

    tasks:
    - id: task_0_1
      name: Початок
      code: glhf
      max_points: 0
      scoring:
      - completed_before: 600000
        percent: 100
      counts_towards_total_time: False

  - name: Етап 1
    duration: 2700
    message: "<b>Інтерактивна частина квесту: <a href='https://vseosvita.ua/webquest/start/s/19358/3608570-657a816a'>vseosvita.ua</a></b>"

    tasks:
    - id: task_1_1
      name: Арифметика 1
      code: "4"
      max_points: 200
      scoring: *default_scoring
    - id: task_1_2
      name: Логіка
      code: "і"
      max_points: 100
      scoring: *default_scoring

    hints:
    - text: '<img src="data:image/gif;base64,R0lGODlhNgAmAPcAAAAAAAICAgMDAwYGBgcHBwgICAoKCgwMDA0NDQ4ODg8PDxAQEBISEhQUFBoaGhsbGx8fHyAgICcnJygoKC8vLzAwMDIyMjQ0NDU1NTY2Njc3Nzg4ODs7Oz09PT4+Pj8/P0FBQUJCQkNDQ0REREVFRUdHR0pKSkxMTE1NTU5OTk9PT1BQUFFRUVRUVFVVVVhYWFlZWVtbW1xcXF5eXmFhYWJiYmNjY2RkZGVlZWZmZmhoaGpqamtra21tbW5ubm9vb3BwcHFxcXd3d3h4eHt7e4CAgIaGhoeHh4iIiIqKiouLi4yMjI6Ojo+Pj5CQkJGRkZKSkpOTk5WVlZaWlpeXl5qampubm5ycnJ2dnZ+fn6CgoKOjo6Wlpaampqenp6ioqKmpqaurq6+vr7GxsbKysra2tre3t7i4uLu7u7y8vL+/v8DAwMLCwsPDw8XFxcnJyc3Nzc7Ozs/Pz9DQ0NHR0dPT09XV1dbW1tfX19jY2NnZ2d3d3d7e3uDg4OHh4eLi4uPj4+Tk5OXl5ebm5ujo6Orq6uzs7O3t7e7u7u/v7/Hx8fLy8vPz8/T09PX19fb29vf39/j4+Pn5+fr6+vv7+/z8/P39/f7+/v///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACwAAAAANgAmAAAI/wAxCRxIsKDBgwgTKsQ0KIeGhRAjSsRUxsSFiQQrNQEE8RAXGAsMCYyzJeGSixgF0qATUcwVKABECvSSBOFJgY54nEiBY5HAQC1scCBx4gimLjYwrolJcIOcgzcxoZAhUAcIgSKCYIoD4I5ADGWUMh1o5AbUi3IA2BH4BwCbSALIYLrEQAumQmMlLpUpMI2Ds5i0BKA0EAGUSgOsYGqUYA8mOAIuCbxkprJlM08J7iU4Z7DBm1k8C0zgBJOPDoa+nBH4psBASz9iy/6RpeDmgXgASPp8ketaTIIArMFkKQgMRAP56BbLF9MbBYAxnZghsMeHgRQyC6zEIA9zgmA8GNcMUwHBkMU7VLC4oUggpAcGMBTRo/KKREIuLAAoAWSgjycpYTJJBlQQMsYKCTCCSR8hWBLgQId4AEmAaEAwkCMCFCKQG0o8iIkkQvTxYBkE1CFQFzEQ1IcfD9LR3oOXDBHBCTVEQZiHOOao4448HiTBj0AGKeSQRBZpJJBV9Kjkkkw26eSTUEYp5ZRUVmnllVg2ScQBAHQJgAlZEqTGHFIwkcgEiTwS5kCSrUAIHi6sWZAiJWCCRRRyEvTEFJjg0EaeJy6A3AgvAIrJBKVhgkQDuxnqqJQBAQA7">'
      timing: 15
    - text: "Відповідь: і"
      timing: 30

  - name: Етап 2
    duration: 2700
    message: "<b>Код від порталу на Етапі 1: ...</b>"

    tasks:
    - id: task_2_1
      name: №1
      code: "Жовтий_Феррарі"
      max_points: 50
      scoring: *default_scoring
    - id: task_2_2
      name: №2
      code: "фізика"
      max_points: 20
      scoring: *default_scoring
    - id: task_2_3
      name: №3
      code: "247"
      max_points: 50
      scoring: *default_scoring
    - id: task_2_4
      name: №4
      code: "нуль"
      max_points: 20
      scoring: *default_scoring
    - id: task_2_5
      name: №5
      code: "ВДЛПФКФН"
      max_points: 70
      scoring: *default_scoring
    - id: task_2_6
      name: №6
      code: "-7"
      max_points: 70
      scoring: *default_scoring
    - id: task_2_7
      name: №7
      code: "карданний_вал"
      max_points: 20
      scoring: *default_scoring
    - id: portal_2
      name: Портал
      code: "Паскаліна_не_відьма"
      max_points: 0
      scoring: *default_scoring

  - name: Етап 3
    duration: 2700
    message: "<b>Етап 2: Портал у Рапунцель, ключ: Ньютон+Лейбніц=інтеграл</b>"

    tasks:
    - id: task_3_1
      name: №1
      code: "loooooooooool2023"
      max_points: 70
      scoring: *default_scoring
    - id: task_3_2
      name: №2
      code: "philox2015"
      max_points: 20
      scoring: *default_scoring
    - id: task_3_3
      name: №3
      code: "takeMeWithYouPlease"
      max_points: 40
      scoring: *default_scoring
    - id: task_3_4
      name: №4
      code: "gaussTop1ever"
      max_points: 40
      scoring: *default_scoring
    - id: task_3_5
      name: №5
      code: "sudoku228"
      max_points: 70
      scoring: *default_scoring
    - id: task_3_6
      name: №6
      code: "5bulls0cows"
      max_points: 60
      scoring: *default_scoring
    - id: portal_3
      name: Портал
      code: "klyatiPogramistu"
      max_points: 0
      scoring: *default_scoring

  - name: Етап 6
    duration: 2700
    message: "<b>Код від порталу на Етапі 5: ...</b>"

    tasks:
    - id: task_6_1
      name: №1
      code: "author"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_2
      name: №2
      code: "pink"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_3
      name: №3
      code: "troll"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_4
      name: №4
      code: "divide"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_5
      name: №5
      code: "math"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_6
      name: №6
      code: "never"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_7
      name: №7
      code: "bone"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_8
      name: №8
      code: "dog"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_9
      name: №9
      code: "equation"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_10
      name: №10
      code: "twelve"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_11
      name: №11
      code: "laugh"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_12
      name: №12
      code: "equals"
      max_points: 15
      scoring: *default_scoring
    - id: task_6_13
      name: №13
      code: "twelve author troll dog bone laugh math equation equals divide pink never"
      max_points: 120
      scoring: *default_scoring
    - id: portal_6
      name: Портал
      code: "the_final_portal"
      max_points: 0
      scoring: *default_scoring
